package com.example.fintrack.data.db

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Bible database blueprint v2.
 *
 * Provenance hierarchy lives in domain/policy/ProvenancePolicy.kt (SourceRank):
 *   USER_CONFIRMED > RAW_EVIDENCE(SMS) > IMPORT_FILE > HEURISTIC > MODEL_SUGGESTION
 * Every interpretation-bearing row carries sourceKind/sourceVersion/reason.
 */

@Entity(
    tableName = "accounts",
    indices = [Index("normalizedName", unique = true)],
)
data class AccountEntity(
    @PrimaryKey val id: String,                 // stable UUID
    val name: String,
    val normalizedName: String,                 // lookup key
    val currencyCode: String,                   // ISO-4217
    val accountType: String,
    val createdAtEpochMs: Long,
    val lifecycle: String,                      // ACTIVE | ARCHIVED
    // v3: authoritative-identity columns. last4 is a *hint* only — duplicates allowed.
    val nickname: String?,
    val last4: String?,                         // exactly 4 digits or null (unknown)
    val institutionName: String?,               // normalized bank/issuer identity
)

@Entity(
    tableName = "messages",
    indices = [
        Index("sourceHash", unique = true),     // dedupe raw evidence
        Index("receivedAtEpochMs"),
    ],
)
data class MessageEntity(
    @PrimaryKey val id: String,
    val body: String,                           // immutable once written
    val sender: String?,
    val receivedAtEpochMs: Long,
    val sourceHash: String,                     // sha-256 of body+sender+timestamp
    val sourceKind: String,
    val sourceVersion: String,
    val capturedAtEpochMs: Long,
)

@Entity(
    tableName = "transactions",
    indices = [
        Index("messageId"),
        Index("occurredAtEpochMs"),             // transaction date lookups
        Index("accountId", "occurredAtEpochMs"),// account/date path
        Index("categoryId"),
        Index("counterpartyNormalized"),        // merchant lookups
        Index("state"),                         // legacy status/processing queues
        Index("status"),                        // P10 normalized lifecycle
        Index("kind"),                          // P10 taxonomy axis
        Index("postingGroupId"),                // P10 posting replacement
        Index("transferGroupId"),               // P11 two-sided transfer siblings
        Index("deletedAtEpochMs"),              // P10 soft-delete tombstones
        Index(value = ["dedupeKey"], unique = true), // idempotency
    ],
)
data class TransactionEntity(
    @PrimaryKey val id: String,
    val messageId: String?,                     // evidence link (null for manual/import)
    val accountId: String,
    val categoryId: String?,
    val amountMinor: Long,                      // integer minor units; NEVER float
    val currencyCode: String,
    val occurredAtEpochMs: Long,                // Instant persistence
    val localDateEpochDay: Long,                // derived local date (deterministic)
    val counterparty: String?,
    val counterpartyNormalized: String?,
    val referenceId: String?,                   // bank ref / UTR etc.
    val state: String,                          // legacy lifecycle (kept for back-compat)
    // provenance of the current interpretation
    val sourceKind: String,
    val sourceVersion: String,
    val sourceReason: String?,
    /** Non-null user correction survives automated reprocessing. */
    val correctionSourceKind: String?,
    val correctionSourceVersion: String?,
    val correctionSourceReason: String?,
    val correctionCapturedAtEpochMs: Long?,
    val dedupeKey: String,                      // hash(account, amount, date, ref)
    // ---- v6 P10 normalized transaction / postings (Stage 5) ----
    /** P10 taxonomy: EXPENSE | INCOME | TRANSFER | REFUND | FEE | CASH_MOVE | UNKNOWN. */
    val kind: String = "UNKNOWN",
    /** Optional subtype (e.g. EXPENSE.UPI, EXPENSE.CARD_POS, REFUND.PARTIAL). */
    val subtype: String? = null,
    /**
     * P10 explicit lifecycle: PENDING | POSTED | REVIEW_REQUIRED | FAILED |
     * DELETED. Authoritative for v6; legacy [state] retained for back-compat.
     */
    val status: String = "POSTED",
    /** Merchant display name, separate from counterparty (counterparty = payee/payer handle). */
    val merchant: String? = null,
    /** Free-form user-visible description; unknown fields stay null. */
    val description: String? = null,
    /** Payment rail (UPI/IMPS/NEFT/RTGS/CARD_POS/CARD_ONLINE/ATM/ACH/UNKNOWN). */
    val rail: String? = null,
    /** Normalized 4-digit card mask; null when no card or unknown. */
    val cardMask: String? = null,
    /**
     * P10 posting-group identity. All [LedgerEntryEntity] rows generated by
     * this transaction share the same value; editing a transaction replaces
     * the entire group inside one @Transaction so duplicate postings can
     * never accumulate.
     */
    val postingGroupId: String? = null,
    /**
     * P11 two-sided transfer identity. Two [TransactionEntity] rows
     * representing the source and destination sides of a transfer share
     * the same value, so listing / detail can show both sides as one
     * logical event. Always null for non-transfer events.
     */
    val transferGroupId: String? = null,
    /** P10 / P11 soft-delete tombstone. null = active; non-null = deleted. */
    val deletedAtEpochMs: Long? = null,
    val deletedReason: String? = null,
)

@Entity(
    tableName = "ledger_entries",
    indices = [
        Index("transactionId"),
        Index("accountId"),
        Index("postingGroupId"),
    ],
)
data class LedgerEntryEntity(
    @PrimaryKey val id: String,
    val transactionId: String,
    val accountId: String,
    val direction: String,                      // DEBIT | CREDIT
    val amountMinor: Long,
    val currencyCode: String,
    /** P10 posting-group identity (shared with parent transaction). */
    val postingGroupId: String? = null,
    /** Free-form memo (e.g. "UPI to Swiggy"). Unknown stays null. */
    val memo: String? = null,
)

@Entity(
    tableName = "categories",
    indices = [
        Index("normalizedName", unique = true),
        Index("parentId"),
        Index("status"),
    ],
)
data class CategoryEntity(
    @PrimaryKey val id: String,
    val name: String,
    val normalizedName: String,
    val parentId: String?,
    // ---- v9 P14 additive columns ----
    /** ACTIVE | ARCHIVED. Archived rows stay queryable for history. */
    val status: String = "ACTIVE",
    /** TAXONOMY | UNCATEGORIZED. UNCATEGORIZED is the singleton unknown sink. */
    val kind: String = "TAXONOMY",
    /** UI ordering hint; uncategorized sorts last. */
    val sortOrder: Int = 0,
    val createdAtEpochMs: Long = 0L,
)

@Entity(
    tableName = "transfers",
    indices = [
        Index("fromEntryId"),
        Index("toEntryId", unique = true),      // an entry can be target of at most one link
    ],
)
data class TransferEntity(
    @PrimaryKey val id: String,
    val fromEntryId: String,
    val toEntryId: String,
    val kind: String,                           // TRANSFER | SETTLEMENT
    val sourceKind: String,
    val sourceVersion: String,
)

@Entity(
    tableName = "processing_jobs",
    indices = [
        Index("status"),                        // processing queue
        Index("nextAttemptAtEpochMs"),
        Index(value = ["jobIdentity"], unique = true), // resumable persisted identity
    ],
)
data class ProcessingJobEntity(
    @PrimaryKey val id: String,
    val jobIdentity: String,                    // stable across restarts
    val jobType: String,
    val payloadRef: String,                     // id of entity to process (no raw payloads)
    val status: String,                         // PENDING | RUNNING | DONE | FAILED
    val attempts: Int,
    val maxAttempts: Int,
    val lastError: String?,
    val nextAttemptAtEpochMs: Long,
)

@Entity(
    tableName = "audit_events",
    indices = [Index("entityId"), Index("atEpochMs")],
)
data class AuditEventEntity(
    @PrimaryKey val id: String,
    val entityId: String,
    val entityType: String,
    val action: String,                         // CREATED | CORRECTED | STATE_CHANGED
    val actor: String,                          // SYSTEM | USER | LLM_VALIDATED
    val detailReason: String?,
    val atEpochMs: Long,
)
