package com.example.fintrack.domain.policy

import com.example.fintrack.domain.model.AccountType
import com.example.fintrack.domain.model.PostingDirection
import com.example.fintrack.domain.model.TransactionV6
import com.example.fintrack.domain.model.TxKind
import com.example.fintrack.domain.model.TxStatus

/**
 * P10 #3 / #4: centralized sign + posting generation.
 *
 * Two facts are invariant across the codebase:
 *  - amountMinor is the absolute value; the sign is encoded in [direction]
 *  - one event = one or more immutable LedgerEntry rows generated by
 *    [generatePostings] inside a single Room @Transaction, so editing a
 *    transaction never accumulates duplicate postings.
 *
 *  - EXPENSE / FEE: DEBIT on the user's account.
 *  - INCOME / REFUND: CREDIT on the user's account.
 *  - TRANSFER: caller passes two events (see [com.example.fintrack.domain.service.TransferService])
 *    and posts both sides explicitly so it can be excluded from income/expense
 *    metrics downstream.
 *  - CASH_MOVE: DEBIT (cash out / ATM) or CREDIT (cash in / deposit) on the
 *    cash account.
 */
object PostingPolicy {

    /**
     * Default direction on a single-account view. For TRANSFER the call site
     * must build TWO postings (one per side) explicitly.
     */
    fun defaultDirection(kind: TxKind): PostingDirection = when (kind) {
        TxKind.EXPENSE, TxKind.FEE, TxKind.CASH_MOVE -> PostingDirection.DEBIT
        TxKind.INCOME, TxKind.REFUND -> PostingDirection.CREDIT
        TxKind.TRANSFER, TxKind.UNKNOWN -> PostingDirection.DEBIT // resolved by caller for TRANSFER
    }

    /**
     * P10 #4: single-sided posting for non-transfer events. Idempotent
     * because the caller always pairs this with a stable postingGroupId
     * and writes everything inside a @Transaction that deletes the prior
     * group first.
     *
     * @return the immutable posting row to persist. The id is supplied by
     *         the caller so the Room write is idempotent.
     */
    fun singlePosting(
        txn: TransactionV6,
        postingId: String,
        postingGroupId: String,
        memo: String?,
    ): SinglePosting = SinglePosting(
        id = postingId,
        transactionId = txn.id.value,
        accountId = txn.accountId.value,
        direction = txn.direction.name,
        amountMinor = txn.amountMinor,
        currencyCode = txn.currencyCode,
        postingGroupId = postingGroupId,
        memo = memo,
    )

    /**
     * P10 #3 signed-amount helper. Returns negative for DEBIT, positive for
     * CREDIT. Empty / unknown amounts remain 0.
     */
    fun signedMinor(amountMinor: Long, direction: PostingDirection): Long =
        if (direction == PostingDirection.CREDIT) amountMinor else -amountMinor

    /**
     * P10 #3 helper: which sign a credit-card account expects on a charge.
     * - BANK / CASH: expenses are DEBIT, refunds are CREDIT.
     * - CREDIT_CARD / OTHER_LIABILITY: purchases are DEBIT (debt grows),
     *   refunds are CREDIT (debt shrinks). The semantic is the same as a
     *   positive cash flow on the user — but the balance is owed, not held.
     */
    fun directionFor(
        kind: TxKind,
        accountType: AccountType,
    ): PostingDirection {
        if (accountType == AccountType.CREDIT_CARD || accountType == AccountType.OTHER_LIABILITY) {
            // For liabilities the sign is inverted because owed-balance grows
            // on charge and shrinks on refund.
            return when (kind) {
                TxKind.EXPENSE, TxKind.FEE, TxKind.CASH_MOVE -> PostingDirection.DEBIT
                TxKind.INCOME, TxKind.REFUND -> PostingDirection.CREDIT
                TxKind.TRANSFER, TxKind.UNKNOWN -> PostingDirection.DEBIT
            }
        }
        return defaultDirection(kind)
    }

    /** Active status (not soft-deleted, not failed). */
    fun isActive(status: TxStatus): Boolean =
        status != TxStatus.DELETED && status != TxStatus.FAILED
}

/** Plain value object representing a single posting row. */
data class SinglePosting(
    val id: String,
    val transactionId: String,
    val accountId: String,
    val direction: String,
    val amountMinor: Long,
    val currencyCode: String,
    val postingGroupId: String,
    val memo: String?,
)
